FROM python:3.12-slim
 
WORKDIR /app
 
COPY src/api/authentification/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
 
COPY src/api/authentification/auth.py .
 
EXPOSE 8001
 
CMD ["uvicorn", "auth:app", "--host", "0.0.0.0", "--port", "8001"]
 